### ISSUE TITLE
Bugs in get ?

### ISSUE THREAD

**Issue by benju69** [orhanobut/hawk#143] opened 2016-04-01 09:13 UTC
Hi 

Crashlytics reports me two exceptions in my app : 

Fatal Exception: java.lang.AssertionError: illegal type variable reference
       at org.apache.harmony.luni.lang.reflect.ImplForVariable.resolve(ImplForVariable.java:113)
       at org.apache.harmony.luni.lang.reflect.ImplForVariable.getGenericDeclaration(ImplForVariable.java:127)
       at org.apache.harmony.luni.lang.reflect.ImplForVariable.hashCode(ImplForVariable.java:46)
       at java.util.Arrays.hashCode(Arrays.java:1260)
       at com.google.gson.internal.$Gson$Types$ParameterizedTypeImpl.hashCode($Gson$Types.java:479)
       at com.google.gson.reflect.TypeToken.(TypeToken.java:64)
       at com.orhanobut.hawk.HawkEncoder$3.(HawkEncoder.java:112)
       at com.orhanobut.hawk.HawkEncoder.toMap(HawkEncoder.java:112)
       at com.orhanobut.hawk.HawkEncoder.decode(HawkEncoder.java:59)
       at com.orhanobut.hawk.Hawk.get(Hawk.java:113)

Fatal Exception: java.lang.AssertionError: illegal type variable reference
       at libcore.reflect.TypeVariableImpl.resolve(TypeVariableImpl.java:110)
       at libcore.reflect.TypeVariableImpl.getGenericDeclaration(TypeVariableImpl.java:124)
       at libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)
       at java.util.Arrays.hashCode(Arrays.java:1261)
       at com.google.gson.internal.$Gson$Types$ParameterizedTypeImpl.hashCode($Gson$Types.java:479)
       at com.google.gson.reflect.TypeToken.(TypeToken.java)
       at com.orhanobut.hawk.HawkEncoder$1.(HawkEncoder.java)
       at com.orhanobut.hawk.HawkEncoder.toList(HawkEncoder.java:76)
       at com.orhanobut.hawk.HawkEncoder.decode(HawkEncoder.java:57)
       at com.orhanobut.hawk.Hawk.get(Hawk.java:113)
       at com.orhanobut.hawk.Hawk.get(Hawk.java:128)

What can I do ?

**Comment by benju69** [comment] 2016-04-04 08:31
Up 
Ah I think is about these missing lines in proguard...
#Gson
-keep class com.google.gson.** { *; }
-keepattributes Signature

**Comment by benju69** [comment] 2016-04-04 09:31
Adding _-keepattributes EnclosingMethod_ to proguard help me apparently :)

**Comment by BinGoBinBin** [comment] 2016-04-11 08:31
when I added " -keepattributes EnclosingMethod",the new crash occured,
`E/AndroidRuntime( 1404): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1404): 	at com.orhanobut.hawk.Logger.log(Logger.java:48)
E/AndroidRuntime( 1404): 	at com.orhanobut.hawk.Logger.d(Logger.java:16)
E/AndroidRuntime( 1404): 	at com.orhanobut.hawk.Hawk.get(Hawk.java:142)
E/AndroidRuntime( 1404): 	at com.malt.tao.b.a.b(DBUtils.java:46)
E/AndroidRuntime( 1404): 	at com.malt.tao.activity.TAOApplication.onCreate(TAOApplication.java:69)
E/AndroidRuntime( 1404): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 1404): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4745)
E/AndroidRuntime( 1404): 	... 10 more
W/ActivityManager(  805):   Force finishing activity com.malt.tao/.activity.FlashActivity`

Any ideals?

**Comment by BinGoBinBin** [comment] 2016-04-11 09:39
I solved it by uninstall my app，the reason may be dirty data~

**Comment by orhanobut** [comment] 2018-04-02 07:56
Seems the problem is solved. 👍 Closing this one for now. We can reopen if it still exists

**Closed by orhanobut** 2018-04-02 07:56 UTC
