### ISSUE TITLE
How long is the connection pool open ?

### ISSUE THREAD

**Issue by imran0101** [orhanobut/hawk#94] opened 2015-10-13 00:07 UTC
Hawk.init(context) is initialised in Application level.
Do I have to initialise every time I try to get or put ?

Singleton Build does not return the object to persist it either.

``` java
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.xxx, PID: 5486
E/AndroidRuntime: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
E/AndroidRuntime:     at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
E/AndroidRuntime:     at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
E/AndroidRuntime:     at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
E/AndroidRuntime:     at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
E/AndroidRuntime:     at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
E/AndroidRuntime:     at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
E/AndroidRuntime:     at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
E/AndroidRuntime:     at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
E/AndroidRuntime:     at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
E/AndroidRuntime:     at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
E/AndroidRuntime:     at com.orhanobut.hawk.SqliteStorage$SqliteHelper.get(SqliteStorage.java:170)
E/AndroidRuntime:     at com.orhanobut.hawk.SqliteStorage.get(SqliteStorage.java:38)
E/AndroidRuntime:     at com.orhanobut.hawk.Hawk.get(Hawk.java:115)
E/AndroidRuntime:     at com.orhanobut.hawk.Hawk.get(Hawk.java:148)
```

**Comment by orhanobut** [comment] 2015-10-13 15:02
Once you initialize it, you wouldn't need to init each time before get or put. I don't know why this is caused actually. Could you show me how did you init Hawk and how did you try to use it?

**Comment by qlyoung** [comment] 2015-11-08 05:46
I encountered this problem as well. In my case, the cause was unsynchronized use of Hawk.get(). I was accessing it in two different AsyncTasks that were running concurrently.
Because the SQLite implementation backing Hawk requires synchronized access, Hawk also has this property. Perhaps you should make that explicit in the library documentation in case anyone encounters this problem in the future.

**Comment by munnadroid** [comment] 2016-04-05 13:26
I am also getting this error alot.

`Fatal Exception: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
       at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
       at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:677)
       at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
       at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
       at com.orhanobut.hawk.SqliteStorage$SqliteHelper.get(SqliteStorage.java:165)
       at com.orhanobut.hawk.SqliteStorage.get(SqliteStorage.java:36)
       at com.orhanobut.hawk.Hawk.get(Hawk.java:117)
       `

**Comment by orhanobut** [comment] 2018-04-02 07:42
Since Sqlite is not supported with the new version, closing this issue.

**Closed by orhanobut** 2018-04-02 07:42 UTC
